GET http://localhost:4000/doctorapp/aniss

###
GET http://localhost:4000
###
POST http://localhost:4000
Content-Type: application/json

{
    "name":"mddd",
    "age" : "33sda",
    "address":"dhsdaka"
}

###

PUT  http://localhost:4000/jeddqvd3-
Content-Type: application/json

{
    "name":"mdddasasdsdss",
    "age" : "3100",
    "address":"dhsaka"
}

###

DELETE  http://localhost:4000/w8ZeCyeKd  

###
POST http://localhost:4000/doctor
Content-Type: application/json

{
    "name":"kanis", 
    "address":"dhanmondi",
    "sector":"surgery",
    "blood_group":"A+"
}